version: '3.8'

services:
#  postgres:
#    image: postgres:latest
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: 12345678
#    ports:
#      - "5432:5432"
#    networks:
#      - botchat-network

  config-server:
    build: ./config-server
    ports:
      - "8888:8888"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    healthcheck:
      test: ["CMD", "curl", "-f", "http://config-server:8888/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - botchat-network

  admin-service:
    build: ./admin-service
    ports:
      - "8081:8081"
    depends_on:
      config-server:
        condition: service_healthy
    networks:
      - botchat-network

  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      config-server:
        condition: service_healthy
    networks:
      - botchat-network

  auth-service:
    build: ./auth-service
    ports:
      - "8082:8082"
    depends_on:
      config-server:
        condition: service_healthy
    networks:
        - botchat-network

  logging-service:
    build: ./logging-service
    ports:
      - "8083:8083"
    depends_on:
      config-server:
        condition: service_healthy
    networks:
        - botchat-network

  user-service:
    build: ./user-service
    ports:
      - "8084:8084"
    depends_on:
      config-server:
        condition: service_healthy
    networks:
        - botchat-network

  chatbot-service:
    build: ./chatbot-service
    ports:
      - "8000:8000"
    depends_on:
      config-server:
        condition: service_healthy
    networks:
        - botchat-network

networks:
    botchat-network:
        driver: bridge